### ISSUE TITLE
Files or document symbols with control characters are not found in ODS

### ISSUE THREAD

**Issue by grozdanic** [dag-hammarskjold-library/ods-api#1]
for T/PET.4&5/L.17

INFO:root:Getting T/PET.4&5/L.17 A ...
WARNING:root:T/PET.4&5/L.17 A not found in ODS
INFO:root:Getting T/PET.4&5/L.17 C ...
WARNING:root:T/PET.4&5/L.17 C not found in ODS
INFO:root:Getting T/PET.4&5/L.17 E ...
WARNING:root:T/PET.4&5/L.17 E not found in ODS
INFO:root:Getting T/PET.4&5/L.17 F ...
WARNING:root:T/PET.4&5/L.17 F not found in ODS
INFO:root:Getting T/PET.4&5/L.17 R ...
WARNING:root:T/PET.4&5/L.17 R not found in ODS
INFO:root:Getting T/PET.4&5/L.17 S ...
WARNING:root:T/PET.4&5/L.17 S not found in ODS
INFO:root:Getting T/PET.4&5/L.17 O ...
WARNING:root:T/PET.4&5/L.17 O not found in ODS

**Comment by jbukhari** [comment]
This was addressed at some point but the issue was never closed
